server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: roole
    static_configs:
      - targets:
          - localhost
        labels:
          job: roole-nodes
          __path__: /var/log/roole/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            node_id: node_id
            cluster: cluster
            component: component
            message: message
      - labels:
          level:
          node_id:
          cluster:
          component:
      - timestamp:
          source: timestamp
          format: RFC3339Nano